<?php

namespace AppBundle\Repository;

/**
 * DateParsingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateParsingRepository extends \Doctrine\ORM\EntityRepository
{
}
