<?php

namespace AppBundle\Repository;

/**
 * ElementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementsRepository extends \Doctrine\ORM\EntityRepository
{
}
