# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.command.yaledaler-parser:
        class: AppBundle\Command\YaledealerParsing
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: console.command }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
